### ISSUE TITLE
Highlight selected Item

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirishareddy/android-wheel#49]
```
What steps will reproduce the problem?
1. Run an application with Text wheel

What is the expected output? What do you see instead?

What I would like to do, is highlight the selected item in a different color. I 
looked at the date examples (which uses a different color for TODAY) and tried 
changing the color is AbstractWheelTextAdapter, this didn't work as don't have 
the notion of selected item. This would mean changing the color each time the 
selection is changed, do you think this is feasible ? Is there an easy way to 
do this ?

What version of the product are you using? On what operating system?
Wheel version 2.1
Android 2.3.3-4.04

```

Original issue reported on code.google.com by `Alexande...@gmail.com` on 2 Apr 2013 at 12:30

**Comment by shirishareddy** [comment]
Can some body please help me on how to change the selected item color and style in wheel view. I have tried using getItem method in the adapter by comparing the index of an item and currentitem but failed.
Any help would be great.

**Comment by shirishareddy** [comment]
I found the solution after lot of trails. While scrolling we are not recreating the item views, instead returning the same view available in WheelView linear layout. Instead we need to recreate the view in rebuildItems() method available in WheelView and set whether the item is current item while getting the view from Adapter.

Here are the changes:
1) WheelView:
private void rebuildItems() {
		ItemsRange range = getItemsRange();
		if (itemsLayout != null) {
			firstItem = recycle.recycleItems(itemsLayout, firstItem, range);
			itemsLayout = null;
		}

		createItemsLayout();

		if (firstItem > range.getFirst() && firstItem <= range.getLast()) {
			for (int i = firstItem - 1; i >= range.getFirst(); i--) {

				if (!addViewItem(i, true)) {
					break;
				}
				firstItem = i;
			}
		} else {
			firstItem = range.getFirst();
		}

		int first = firstItem;
		for (int i = itemsLayout.getChildCount(); i < range.getCount(); i++) {
			if (!addViewItem(firstItem + i, false) && itemsLayout.getChildCount() == 0) {
				first++;
			}
		}
		firstItem = first;
	}
	

2) WheelViewAdapter:
/**
	 * Get a View that displays the data at the specified position in the data set
	 * 
	 * @param index the item index
	 * @param convertView the old view to reuse if possible
	 * @param parent the parent that this view will eventually be attached to
	 * @return the wheel item View
	 */
	View getItem(int index, View convertView, ViewGroup parent);

3) AbstractWheelTextAdapter:

 public View getItem(int index, View _convertView, ViewGroup parent, boolean isCurrentItem) {
        if (index >= 0 && index < getItemsCount()) {

            View convertView = (_convertView == null) ? getView(itemResourceId, parent) : _convertView;

            TextView textView = getTextView(convertView, itemTextResourceId);

            if (textView != null) {
                CharSequence text = getItemText(index);
                textView.setText( (text == null)? "":text);

                if (itemResourceId == TEXT_VIEW_ITEM_RESOURCE) {
                    configureTextView(textView);
                }

                if(isCurrentItem){
                    textView.setTypeface(textViewTypeFaceBold);
                }else {
                    textView.setTypeface(textViewTypeFaceNormal);
                }
            }

            return convertView;
        }
        return null;
    }

4) WheelRecycle:
public int recycleItems(LinearLayout layout, int firstItem, ItemsRange range) {
		int index = firstItem;
		for (int i = 0; i < layout.getChildCount(); i++) {
				recycleView(layout.getChildAt(i), index);
				layout.removeViewAt(i);
				if (i == 0) { // first item
					firstItem++;
				}
			index++;
		}
		return firstItem;
	}
